/*
 Ejemplo del manejo de archivos en Java, Lectura y Escritura utilizando JFileChooser
 */

package archivos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author NetoSolis-
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCad = new javax.swing.JTextArea();
        lbLin = new javax.swing.JLabel();
        lbCar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCad.setColumns(20);
        txtCad.setRows(5);
        jScrollPane1.setViewportView(txtCad);

        lbLin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbLin.setText("No de Lineas");

        lbCar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbCar.setText("No de Caracteres");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Abrir Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Guardar Archivo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Reemplazar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLin)
                    .addComponent(lbCar))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //Instruccion para terminar la ejecuion
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Con esta funcion vamos a abrir un archivo txt
        try{
            //Declaramos el objeto JFileChooser 
            JFileChooser chooser = new JFileChooser();
            //Le decimos que solo acepte archivo txt
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos txt","txt");
            chooser.setFileFilter(filter);
            //Mostramos la ventana 
            chooser.showOpenDialog(this);
            //Tomamos el archivo que se selecciono
            File open=chooser.getSelectedFile();
            String cad="";
            //Verificamos que se haya seleccionado un archivo
            if(open!=null){
               //Creamos un buffer para leer el archivo
               FileReader archivo=new FileReader(open);
               BufferedReader buffer=new BufferedReader(archivo);
               //Inicializamos variables para contar caracteres y numero de lineas del archivo
               int noLineas = 0;
               int noCar = 0;
               //Limpiamos el area de texto
               txtCad.setText("");
               //Empezamos a leer linea a linea el archivo y las agregamos al area de texto
               while((cad=buffer.readLine())!=null){
                  noLineas++;
                  noCar += cad.length();
                  txtCad.append(cad+"\n");
               }
               //Mandamos escribir el numero de lineas y de caracteres
               lbLin.setText("No de Lineas: "+noLineas);
               lbCar.setText("No de Caracteres: "+noCar);
               //cerramos el buffer
               buffer.close();
             }
            else{
                JOptionPane.showMessageDialog(rootPane, "Error Al Abrir El Archivo");
            }
         }
         catch(IOException ex){
           JOptionPane.showMessageDialog(rootPane, "Error Al Abrir El Archivo: "+ex);
         }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Funcion para guardar un archivo
        try{
            //Inicializamos el objeto JFileChooser
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos txt","txt");
            chooser.setFileFilter(filter);
            //Abrimos la ventana para guardar
            chooser.showSaveDialog(this);
            //Tomamos el archivo seleccionado
            File archivo = chooser.getSelectedFile();
            //Comprobamos que se selecciono un archivo
            if(archivo != null){
              //Creamos el objeto FileWriter que nos ayudara a escribir en el archivo
              FileWriter   file = new FileWriter(archivo);
              //Variables para contrar las lineas y caracteres del texto
              String [] split = txtCad.getText().split("\n");
              int noCar = 0;
              for(int i = 0; i < split.length; i++) {
                  noCar += split[i].length();
              }
              //Escribimos en el archivo y lo cerramos
              file.write(txtCad.getText());
              file.close();
              //Mandamos a escribir el numero de lineas y de caracteres del texto guardado
              lbLin.setText("No de Lineas: "+split.length);
              lbCar.setText("No de Caracteres: "+noCar);
              JOptionPane.showMessageDialog(null,"El Archivo Fue Guardado Exitosamente");
           }
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null,"Error Al Guardar El Archivo: "+ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //Funcion para reemplazar
        try {
            //Tomamos el texto del area de texto
            String cad = txtCad.getText();
            //Pedimos al usuario la palabra a reemplzar y la nueva palabra
            String buscar = JOptionPane.showInputDialog("Palabra a Reemplazar");
            String nueva = JOptionPane.showInputDialog("Palabra Nueva");
            //Cambiamos el texto por el nuevo reemplzando la palabra
            txtCad.setText(cad.replace(buscar, nueva));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Error Con el Reemplazo: "+ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCar;
    private javax.swing.JLabel lbLin;
    private javax.swing.JTextArea txtCad;
    // End of variables declaration//GEN-END:variables
}
